module.json
readme.md

This corrects the links in the module, the readme file.
@bogdanm @bremoran

Module and readme - set correct github links. Fixes #80

---

mbed/pinmap_common.h
source/pinmap_common.c

This should fix reported problem of missing definitions for pinmap_function().
References:
- mbed-hal - https://github.com/ARMmbed/mbed-hal/pull/19
Tested with st target which uses pinmap_function() and k64f. A note, the implementation is from mbed - no changes in those 2 functions.
@bogdanm @bremoran

Adding pinmap function

---

source/retarget.cpp

mbed_hal_init (formerly mbed_sdk_init) is a strong declared. This change will require to be mbed_hal_init defined in target's hal. Therefore before merging, I'll need to reference changes in our HAL.
There's still wrapping the main, this can be factored out as we define main. Or at least, mbed_hal_init() invoked in main, this wrapping stays empty.
References:
- mbed-hal - https://github.com/ARMmbed/mbed-hal/pull/20
- hal-frdm-k64f- - https://github.com/ARMmbed/mbed-hal-frdm-k64f/pull/8
- hal-stmf4 - https://github.com/ARMmbed/mbed-hal-st-stm32f4/pull/11
@bogdanm @bremoran @autopulated @rgrover

[breaking change] mbed_sdk_init rename to mbed_hal_init

---

mbed/SPI.h
source/SPI.cpp

When using invalid buffers, the callback chain is intentionally broken,
since no callback is ever called.
This should never be a silent failure, even on user error.
In fact, `SPI_EVENT_ERROR` should be non-maskable and there should always be an error check in the callback.
If the user really does not want a callback, it can still be set to `NULL`.
@0xc0170 @bremoran

SPI: Issue error callback on buffer validation failure.

---

test/asynch_spi/asynch_spi.cpp

This test would fail to compile for a target != K64F with asynch defined.
And even TARGET_K64F, should be TARGET_LIKE_FRDM_K64F. I can add that
@bogdanm @bremoran @marcuschangarm

Tests - SPI - fix supported targets

---

source/SerialBase.cpp

Removal of width parameter, use 0 for hal functions invocation (deprecated - not used).
Unfortunately, this is breaking change. Although we could define new method without width parameter and current one would invoke it with predefined ignored value. Or any other idea?
@bogdanm

Serial - removal of unused width parameter in write/read

---

mbed-drivers/SPI.h
source/SPI.cpp

Additions:
- busy flag - per object to reflect that transfer is ongoing (started, about to start) - the flag is not static - because for example SPI_0 does not block SPI_1 module.
- critical locks for queue actions -  we have currently one queue for all spi modules - there can be multiple reader/writers
@bogdanm @bremoran

Fix for #ksdk-issue-8 - spi busy for asynch

---

source/InterruptIn.cpp

Reported here https://github.com/ARMmbed/mbed-hal-st-stm32f4/issues/28. A user reported  it fixes the issue.
@bogdanm

InterruptIn - raise/fall deregister - clear fp and check in irq handler

---

mbed-drivers/Stream.h
source/Stream.cpp

Makes logging a little easier and more consistent in implementation. Also fewer local buffers.
```
void trace(const char* format, ...)
{
va_list argp;
va_start(argp, format);
vprintf(format, argp);
va_end(argp);
}
```

add variable arguemnt support to stream

---

source/retarget.cpp

The default baud rate for tests needs to be much higher to support dumping coverage information. Make the default baud rate configurable via yotta config.

Add a default baud rate assignment via yotta config

---

source/retarget.cpp

Add preprocessor directives to redefine the value of `OPEN_MAX` to `YOTTA_CFG_MBED_MAX_FILEHANDLES`, a macro defined through yotta. This enables users to manually set the size of the `filehandles` array through a yotta config file and get some memory savings.
@bogdanm @0xc0170

Add redefinition of OPEN_MAX through yotta

---

mbed-drivers/test_env.h
source/retarget.cpp
source/test_env.cpp

Add coverage start/end blocks
Add a flag variable that indicates whether a coverage dump is in progress
Override file handle 3 while code coverage is active to indicate coverage output
Override _write() on file handle 3 while code coverage is active to hex-encode all data. Note that gcov uses single-byte writes, so base64 encoding would require global state.
Override _open() while code coverage is active: dump file name in a coverage block header, and return file handle 3
Override _close(3) while code coverage is active: dump a coverage block footer

Add support for code coverage

---

mbed-drivers/app.h
mbed-drivers/mbed.h
source/retarget.cpp

As decribed in #136 and #118, app.h is redundant and problematic.
This commit replaces the previous code in app.h with a deprecation
warning, instead of removing it completely, to keep compatibility
with code that includes "app.h" explicitly.
Tested by compiling mbed-drivers, minar and core-util with
mbed-k64f-gcc and mbed-k64f-armcc.

Disable app.h

---

source/retarget.cpp

All the initialization related to console operations (stdout/stderr/stdin)
now happens in retarget.cpp. The relevant parts will be removed from the
target specific code in subsequent commits.

Changed console initialization

---

source/retarget.cpp

Some toolchains might not call open() for stdio handles prior main, which breaks usage:
```
void app_start(int, char**)
{
Serial pc(tx, rx);
pc.baud(115200);
printf("sss \n"); //open stdio might happen here
}
```
An example above was not working for our gcc targets.
A note: YOTTA_CFG_MBED_OS_STDIO_DEFAULT_BAUD in this case is the one which is set, no matter what SerialBase ctor sets (if Serial() object (for USBTX,USBRX) is in a global scope, sets baudrate within ctor to different value than YOTTA_CFG_MBED_OS_STDIO_DEFAULT_BAUD), still get overwritten by YOTTA_CFG_MBED_OS_STDIO_DEFAULT_BAUD. Just stating this for a future reference
@bogdanm @pan-

Retarget - main - invoke serial init

---

mbed-drivers/Serial.h
readme.md
source/retarget.cpp
test/serial_interrupt/main.cpp

We provide mbed::get_serial_stdio() to get a reference for stdio Serial
object. We should discourage to use Serial pc(USBTX, USBRX)
We should clean our tests/examples, to use this new function for stdio Serial operations like baud(), format() or any other.
Should fix #140
@marcuschangarm @bogdanm @pan- @bremoran

Retarget - stdio serial lazy initialization

---

mbed-drivers/SPI.h

Backwards compatible with `mbed-hal-<chip>/target_config.h`.
@bogdanm @bremoran @0xc0170 @mjs-arm

Add yotta config defaults for SPI transaction queue size.

---

source/retarget.cpp
source/test_env.cpp

When mbed-drivers moved to lazy init of stdio, it introduced a fopen call. This fopen happened to use filehandle 3 for a serial port. Since gcov used filehandle 3, this caused contention with serial.
To fix this, several actions were required:
* Change gcov's file handle to something outside the range of the filehandles we typically allocate
* Trap calls to _read, _write, _lseek, and _fstat on the gcov file handle
* Add explicit checks for the gcov file handle in _write and _close
* Switch from using gcov_exit to __gcov_flush
cc @0xc0170 @PrzemekWirkus @bogdanm

Fix gcov code coverage generation

---

.gitignore
Doxyfile
docs/I2C.md
mbed-drivers/v2/EphemeralBuffer.hpp
mbed-drivers/v2/I2C.hpp
mbed-drivers/v2/I2CDetail.hpp
source/v2/EphemeralBuffer.cpp
source/v2/I2C.cpp
source/v2/I2CDetail.cpp

Much in the same vein as https://github.com/ARMmbed/mbed-drivers/pull/93, add a fluent API to I2C
cc @0xc0170 @bogdanm @salkinium @hugovincent @autopulated

Add a prototype fluent API for I2C

---

source/v2/I2C.cpp

Partly fixes #166 . However, as expected, if CORE_UTIL_ASSERT is not active (NDEBUG defined), this results in the warning:
`` warning: unused variable 'result' [-Wunused-variable] I2CError result = _owner->init(sda, scl); ``
We might want to use error() for this:
```
if (I2CError::None == _owner->init(sda, scl)) {
error("I2C init failed with an error");
}
```
@bogdanm @bremoran

I2C - init() call out of the assert

---

mbed-drivers/test_env.h
source/retarget.cpp
source/test_env.cpp

* This reverts commit d8bb796. (unfortunate deletion of test_env.* files)
* Use of ```test_env```:
* If greentea-client dependency use greentea-client/test_env.h and greentea_*
function from this module.
* If no greentea-client dependency use mbed-drivers/test_env.h with old
functionality.
* See changes from PR: [[devel_transport_update] mbed-drivers with test_env alignment](https://github.com/ARMmbed/greentea-client/pull/2).
* Above changes do not brake ```utest``` v1.10.0 ```greentea-client``` ```~0.1.5``` dependencies.
* ```greentea-client``` should be released after above PR to version ```~0.1.6``` (patch version +1).
* Users using only unity for their tests with pre Async model should stick to unity v1.9.x,

[devel_transport_update] Devel transport updates - test_env and retarget issues.

---

mbed-drivers/pinmap_common.h
source/pinmap_common.c
source/v2/I2C.cpp

Selects the instance by finding unique peripheral IDs in the pinmap.
Fixes #166 
cc @0xc0170 @marcuschangarm @bogdanm

Add a target-independent instance selector

---

DOXYGEN_FRONTPAGE.md

Doxygen on docs.mbed requires a front page file under the name DOXYGEN_FRONTPAGE.md. This is just a copy of the repo's readme. I will look into transclusion options later on, and if they work I'll replace the contents of this page with a link to the original readme.

Creating the doxygen front page

---

mbed-drivers/mbed_debug.h

Without this mbed always generates warnings for these unused parameters.

Fix warnings in mbed_debug.h

---

source/ticker_api.c

Calling any of the mbed::Ticker function will unlock a mbed::util::CriticalSectionLock
Fixes #192

Replaced __enable_irq()/__disable_irq() with critical sections
